### ISSUE TITLE
Installation fails: Invalid appinfo.xml file found: Element 'types'

### ISSUE THREAD

**Issue by whizzrd** [nextcloud/maps#604]
```
occ app:install maps
Error: The "unique" column option is not supported.
```
```
occ migrations:status maps
In MigrationService.php line 508:                                  
  Migration step 'OCA\Maps\Migration\Version000008Date20190428142257' is unknown  
```
```
occ app:check-code maps
Analysing /var/www/html/custom_apps/maps/lib/Service/FavoritesService.php
 1 errors
    line  690: == - is discouraged
Invalid appinfo.xml file found: Element 'types': This element is not expected. Expected is one of ( contactsmenu, collaboration, sabre, trash, versions ).

App is not compliant
```
```
grep version nextcloud/custom_apps/maps/appinfo/info.xml 
<?xml version="1.0"?>
    <version>0.1.8</version>
        <nextcloud min-version="20" max-version="21"/>
```
```
occ status
  - installed: true
  - version: 21.0.1.1
  - versionstring: 21.0.1
  - edition: 
  ```
